/**
 * SkillsHome brand tokens — "Ascending Facets" identity, Brass on Warm Black.
 *
 * ** This file is the only place a brand hex is written. ** Everything downstream
 * (theme/tokens.css, logo/assets/*) is generated by ../scripts/build-tokens.mjs — run
 * `npm run build` after any change here and commit the regenerated output.
 *
 * BRAND is the core identity used by the logo (see ../logo/SkillsHomeLogo.tsx) —
 * do not recolour outside this set. LIGHT_THEME is the primary app-chrome palette
 * (white surfaces, brass accents, warm neutrals) used across the main product.
 * DARK_THEME is the warm-black skin used for marketing pages, admin, and legal
 * surfaces. Both take their brand hue from BRAND — the single accent is brass
 * `#E8B04B`, recolored 2026-09-03 from LinkedIn blue `#0077b5` (which ran
 * 2026-08-02 to 2026-09-03, itself a revert of the 2026-07-27 purple).
 *
 * On white, brass `#E8B04B` fails AA as a text/link color (~1.8:1), so the two
 * themes deliberately diverge: LIGHT_THEME.primary is `bronze` (a dark gold that
 * clears 4.5:1 on white) for links and text, and `#E8B04B` appears on light
 * surfaces only as a *fill* carrying dark `onAccent` text — the CTA-button
 * treatment from the marketing mock. On the warm-black DARK_THEME, brass is
 * bright enough to be the accent directly.
 *
 * Multiple themes are available:
 * - LIGHT_THEME: Primary app-chrome (white bg, brass accents, warm neutrals) — current default
 * - DARK_THEME: Marketing / admin / legal warm-black skin (brass accents)
 * - CONSOLE_THEME: Archived console theme (lime/charcoal)
 * - LATTICE_THEME: Archived dark-first design system (oklch-based, graph-native)
 *
 * A future white-labeled tenant would likely swap LIGHT_THEME/DARK_THEME but keep BRAND,
 * or swap both.
 *
 * The scoring triad (scoreSelf / scoreSystem / scoreVerified) stays a *distinct*
 * three-colour set here — self=brass, system=violet, verified=green — because the
 * product's score UI is unreadable if the three collapse to one hue. The marketing
 * surfaces render the triad as a brass monochrome ramp on their own; that ramp is
 * not defined here.
 *
 * Only the brand-hue fields moved in this recolor (primary/accent/info/scoreSelf
 * and their tints/hovers) plus a warm shift of the light neutrals to sit under
 * brass. success/warning/error/scoreSystem/scoreVerified are unchanged; info
 * folds into the bronze primary (a cool info hue read as non-brand).
 *
 * Every foreground/background pair is WCAG-checked by ../scripts/check-contrast.mjs
 * (`npm run check:contrast`) — that script, not a hand-maintained table, is the authority.
 */

export const BRAND = {
  brassDeep: '#3A2F22',
  bronze: '#856416',
  brass: '#E8B04B',
  brassLight: '#F2CF8D',
  white: '#FFFFFF',
} as const;

/** Primary app-chrome theme — white surfaces, brass accents, warm neutrals. */
export const LIGHT_THEME = {
  // Surfaces
  bg: '#FAF8F4',
  panel: '#FFFFFF',
  panel2: '#F5F1E9',
  line: '#E9E3D6',
  lineStrong: '#D4C9B4',

  // Text
  ink: '#1E1913',
  ink2: '#5C5344',
  ink3: '#8A7E6A',

  // Primary / interactive
  primary: '#856416',
  primaryHover: '#634B10',
  primaryTint: '#F7EDD8',
  accent: '#E8B04B',
  onAccent: '#1A1206',

  // Scoring triad (self-assessed / system-evaluated / verified) — kept distinct
  scoreSelf: '#856416',
  scoreSystem: '#6E42CC',
  scoreVerified: '#057642',

  // Semantic
  success: '#057642',
  warning: '#B45309',
  error: '#CC1016',
  info: '#856416',

  sans: '"Sora", system-ui, sans-serif',
  serif: '"Newsreader", Georgia, serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

/**
 * Marketing / admin portal / legal-page warm-black skin. Warm-black surfaces,
 * brass accents, warm-grey ink ramp — the palette of the "Brass on Warm Black"
 * marketing mock. Neutrals are a warm ramp (#100D0B … #F7F4EE), distinct from
 * LATTICE_THEME's cool near-black.
 */
export const DARK_THEME = {
  bg: '#100D0B',
  panel: '#191410',
  panel2: '#0B0908',
  ink: '#F7F4EE',
  ink2: '#A29A8C',
  ink3: '#736A5C',
  line: '#2A2320',
  accent: '#E8B04B',
  onAccent: '#1A1206',
  acBg: '#241C11',
  grid: 'rgba(232,176,75,.05)',

  // Scoring triad, brightened for warm-black surfaces
  scoreSelf: '#E8B04B',
  scoreSystem: '#9A7BE8',
  scoreVerified: '#3DDC97',

  sans: '"Sora", system-ui, sans-serif',
  serif: '"Newsreader", Georgia, serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

/**
 * Archived original "Console" (lime/charcoal) theme — retained so the look can be
 * restored or referenced. Also available as the `console` Facet theme in skillshome-app.
 */
export const CONSOLE_THEME = {
  bg: '#0d0e0a',
  panel: '#141611',
  panel2: '#101208',
  ink: '#eef0e2',
  ink2: '#9b9e8c',
  ink3: '#6a6d5d',
  line: '#25271d',
  accent: '#b6f04a',
  acBg: '#1c2410',
  grid: 'rgba(182,240,74,.05)',
  sans: '"Space Grotesk", system-ui, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

/**
 * Archived — Lattice, a dark-first design system ported from ThinkAI.Social.
 * Uses oklch color space for precise perceptual control.
 * Four semantic edge-type hues: cite, elaborate, challenge, synthesise.
 * Kept for reference / possible future graph-native surfaces.
 */
export const LATTICE_THEME = {
  bgVoid: '#0a0a0a',
  bg0: '#0f0f0f',
  bg1: '#1a1a1a',
  bg2: '#252525',
  bg3: '#303030',

  lineSoft: '#3a3a3a',
  line: '#505050',

  fg3: '#5a5a5a',
  fg2: '#888888',
  fg1: '#c8c8c8',
  fg0: '#f8f8f8',

  cite: 'oklch(0.72 0.15 248)',
  elaborate: 'oklch(0.76 0.15 168)',
  challenge: 'oklch(0.73 0.16 42)',
  synthesise: 'oklch(0.71 0.17 295)',

  brand: 'oklch(0.71 0.17 288)',
  brandDim: 'oklch(0.58 0.13 288)',
  ok: 'oklch(0.76 0.15 168)',
  warn: 'oklch(0.80 0.15 85)',
  crit: 'oklch(0.66 0.20 25)',

  userScore: 'oklch(0.72 0.15 248)',
  systemScore: 'oklch(0.71 0.17 295)',
  verifiedScore: 'oklch(0.76 0.15 168)',

  sans: '"Space Grotesk", system-ui, sans-serif',
  serif: '"Newsreader", Georgia, "Times New Roman", serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

export type BrandPalette = typeof BRAND;
export type LightThemePalette = typeof LIGHT_THEME;
export type DarkThemePalette = typeof DARK_THEME;

export type ThemeId = 'light' | 'dark' | 'console' | 'lattice';
