/**
 * SkillsHome brand tokens — "Ascending Facets" identity, Brass on Warm Black.
 *
 * ** This file is the only place a brand hex is written. ** Everything downstream
 * (theme/tokens.css, logo/assets/*) is generated by ../scripts/build-tokens.mjs — run
 * `npm run build` after any change here and commit the regenerated output.
 *
 * 2026-09-04: re-authored from the design team's approved "Brass on Warm Black"
 * system (design_system_brass package). Replaces the LinkedIn-blue identity
 * (2026-08-02) and my earlier interpretation (7695e84). Key rules from the spec:
 *
 *  - The neutral ramp is re-hued warm, not just accent-swapped. Every DARK_THEME
 *    step is the previous cool-grey step shifted to hue ~82 at matching lightness.
 *  - The three-score scale is a VALUE ramp inside one hue family — there is no
 *    green and no violet anywhere: claimed `line #5a5045` → AI-inferred
 *    `brass #e8b04b` → verified `brassLight #f4d79a`. On light surfaces the ramp
 *    necessarily darkens instead of brightening (brass is ~1.8:1 on white).
 *  - `warn` is burnt orange `#d97742`, NOT amber — the single deliberate hue
 *    break in the system, which is why an alarm still reads as an alarm.
 *  - `brassInk #1a1206` is the one near-black authored rather than reused: it is
 *    the text/icon colour on a filled brass surface (9.5:1 on #e8b04b).
 *  - The logo mark has NO background tile and brightens DOWNWARD (top chevron
 *    `brassDeepMark #9c7530` darkest). See ../logo/SkillsHomeLogo.tsx and
 *    ../scripts/build-tokens.mjs.
 *
 * BRAND is the core identity used by the logo — do not recolour outside this set.
 * DARK_THEME (warm-black) is the primary product + marketing + admin skin; nearly
 * every page renders on it via lib/tokens.ts / ConsoleNav's `C`. LIGHT_THEME is
 * the white-surface skin used by the `brand` Facet theme's light mode (public
 * profiles) — the spec is dark-only, so LIGHT_THEME is a warm-brass extrapolation.
 *
 * Multiple themes are available:
 * - DARK_THEME: warm-black brass skin — product, marketing, admin, legal (default)
 * - LIGHT_THEME: white-surface warm-brass skin — `brand` Facet light mode
 * - CONSOLE_THEME: Archived console theme (lime/charcoal)
 * - LATTICE_THEME: Archived dark-first design system (oklch-based, graph-native)
 *
 * Every foreground/background pair is WCAG-checked by ../scripts/check-contrast.mjs
 * (`npm run check:contrast`) — that script, not a hand-maintained table, is the authority.
 */

export const BRAND = {
  /** De-emphasised accent work — secondary underlines, muted borders, --brand-dim.
   *  Not for text on the warm-black bg. */
  brassDeep: '#3a2f22',
  /** Logo TOP (darkest) chevron. A graphic value only — 4.6:1, never text. */
  brassDeepMark: '#9c7530',
  /** Primary accent. Every accent surface resolves here. 9.9:1 on bg #100d0b. */
  brass: '#e8b04b',
  /** Light brass — link hover, the BOTTOM (brightest) logo chevron, and the
   *  "verified" score signal (this system has no green). 13.9:1 on bg. */
  brassLight: '#f4d79a',
  /** Text/icons on a filled brass surface. 9.5:1 on #e8b04b. The one near-black
   *  authored rather than reused (bg-0 on brass scores higher but reads cold). */
  brassInk: '#1a1206',
  /** Deep brass that carries white/near-white text (7.3:1 on white). The logo's
   *  light-variant leading edge, LIGHT_THEME.primary, and admin filled buttons. */
  bronze: '#6d5120',
  white: '#ffffff',
} as const;

/**
 * Warm-black skin — the primary product, marketing, admin and legal palette.
 * Neutral ramp per design_system_brass README §3 (each step the old cool-grey
 * step re-hued warm at matching lightness).
 */
export const DARK_THEME = {
  // Surfaces
  void: '#080706',        // canvas behind page mocks only
  bg: '#100d0b',          // page background            (--bg-0)
  band: '#0b0908',        // alternating section band   (--bg-band)
  panel: '#171310',       // panel surfaces             (--bg-1)
  panel2: '#241f1b',      // raised surfaces, chat bubbles (--bg-2)
  panel3: '#2f2823',      // (--bg-3)

  // Lines
  lineFaint: '#211b17',   // in-band divider (editorial hairline)
  lineSoft: '#3a3229',    // input underlines, secondary button borders
  line: '#5a5045',        // borders; also the "self-claimed" score bar fill

  // Foreground ramp — same lightness as before, re-hued warm
  ink: '#f7f4ee',         // headings, primary text (warm white)   (--fg-0) 17.7:1
  inkLede: '#efe9de',     // 23–27px Newsreader ledes / pull quotes (--fg-lede) 16.1:1
  ink1: '#c8c0b3',        // body prose                            (--fg-1) 10.8:1
  ink2: '#a29a8c',        // secondary body prose                  (--fg-2) 7.0:1
  ink3: '#736a5c',        // DECORATIVE ONLY — mono eyebrows, numerals, captions (--fg-3) 3.6:1

  // Brand + accent
  accent: '#e8b04b',      // (--brand) 9.9:1
  accentDim: '#3a2f22',   // (--brand-dim)
  accentInk: '#1a1206',   // text/icons on a filled brass surface (--accent-ink) 9.5:1
  onAccent: '#1a1206',    // alias of accentInk (legacy call sites)
  acBg: '#41321c',        // color-mix(brass 20%, panel) — accent-tint background
  grid: 'rgba(232,176,75,.05)', // color-mix(brass 5%, transparent) — grid lines

  // Three-score scale — a VALUE ramp in one hue, no green / no violet
  scoreSelf: '#5a5045',   // claimed        (= line)
  scoreSystem: '#e8b04b', // AI-inferred    (= accent)
  scoreVerified: '#f4d79a', // verified     (= ok / brassLight)

  // Status
  ok: '#f4d79a',          // verified, pass, JD match — polished brass, not green
  warn: '#d97742',        // beta chips, skill gaps, [TBD] — the one hue break
  crit: '#e5484d',
  success: '#f4d79a',     // "positive" states — brass, not green (spec §3.2)
  warning: '#d97742',
  error: '#e5484d',
  info: '#e8b04b',

  // Logo chevron ramp — brightens DOWNWARD (top darkest)
  logoDeep: '#9c7530',
  logoMid: '#e8b04b',
  logoBright: '#f4d79a',

  sans: '"Sora", system-ui, sans-serif',
  serif: '"Newsreader", Georgia, serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

/**
 * White-surface skin — `brand` Facet light mode (public profiles). The approved
 * spec is dark-only; this is a warm-brass extrapolation. Because brass is ~1.8:1
 * on white, the score ramp here DARKENS toward "verified" instead of brightening,
 * and `primary` is a deep brass (`#6d5120`, 6.6:1) drawn from the logo's light
 * variant. `accent #e8b04b` appears only as a fill with dark `onAccent` text.
 */
export const LIGHT_THEME = {
  // Surfaces
  bg: '#faf7f2',
  panel: '#ffffff',
  panel2: '#f4efe6',
  line: '#e7e0d2',
  lineStrong: '#d3c7b2',

  // Text (warm)
  ink: '#1c1712',
  ink2: '#5b5344',
  ink3: '#8a7e6a',

  // Primary / interactive
  primary: '#6d5120',       // deep brass — links, text, nav active (6.6:1 on white)
  primaryHover: '#4f3a16',
  primaryTint: '#f7ecd6',
  accent: '#e8b04b',        // CTA fill — dark onAccent text only
  onAccent: '#1a1206',

  // Three-score scale — value ramp, darkening toward "verified"
  scoreSelf: '#8f7d63',     // claimed (muted, non-text bar fill)
  scoreSystem: '#b3812c',   // AI-inferred (mid brass)
  scoreVerified: '#6d5120', // verified (deep brass)

  // Semantic — no green; "success" folds into the verified/primary deep brass
  success: '#6d5120',
  warning: '#b8541f',       // burnt orange, darkened for white
  error: '#cc1016',
  info: '#6d5120',

  sans: '"Sora", system-ui, sans-serif',
  serif: '"Newsreader", Georgia, serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

/**
 * Archived original "Console" (lime/charcoal) theme — retained so the look can be
 * restored or referenced. Also available as the `console` Facet theme in skillshome-app.
 */
export const CONSOLE_THEME = {
  bg: '#0d0e0a',
  panel: '#141611',
  panel2: '#101208',
  ink: '#eef0e2',
  ink2: '#9b9e8c',
  ink3: '#6a6d5d',
  line: '#25271d',
  accent: '#b6f04a',
  acBg: '#1c2410',
  grid: 'rgba(182,240,74,.05)',
  sans: '"Space Grotesk", system-ui, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

/**
 * Archived — Lattice, a dark-first design system ported from ThinkAI.Social.
 * Uses oklch color space for precise perceptual control.
 * Four semantic edge-type hues: cite, elaborate, challenge, synthesise.
 * Kept for reference / possible future graph-native surfaces.
 */
export const LATTICE_THEME = {
  bgVoid: '#0a0a0a',
  bg0: '#0f0f0f',
  bg1: '#1a1a1a',
  bg2: '#252525',
  bg3: '#303030',

  lineSoft: '#3a3a3a',
  line: '#505050',

  fg3: '#5a5a5a',
  fg2: '#888888',
  fg1: '#c8c8c8',
  fg0: '#f8f8f8',

  cite: 'oklch(0.72 0.15 248)',
  elaborate: 'oklch(0.76 0.15 168)',
  challenge: 'oklch(0.73 0.16 42)',
  synthesise: 'oklch(0.71 0.17 295)',

  brand: 'oklch(0.71 0.17 288)',
  brandDim: 'oklch(0.58 0.13 288)',
  ok: 'oklch(0.76 0.15 168)',
  warn: 'oklch(0.80 0.15 85)',
  crit: 'oklch(0.66 0.20 25)',

  userScore: 'oklch(0.72 0.15 248)',
  systemScore: 'oklch(0.71 0.17 295)',
  verifiedScore: 'oklch(0.76 0.15 168)',

  sans: '"Space Grotesk", system-ui, sans-serif',
  serif: '"Newsreader", Georgia, "Times New Roman", serif',
  mono: '"JetBrains Mono", ui-monospace, monospace',
} as const;

export type BrandPalette = typeof BRAND;
export type LightThemePalette = typeof LIGHT_THEME;
export type DarkThemePalette = typeof DARK_THEME;

export type ThemeId = 'light' | 'dark' | 'console' | 'lattice';
