/**
 * Generates every derived artifact from theme/tokens.ts — the single source of hex.
 *
 * Outputs:
 *   theme/tokens.css    CSS custom properties, for consumers whose styles can't
 *                       import a .ts module (globals.css, facet.css, Tauri CSS)
 *   logo/assets/*.svg   static mark variants
 *
 * Run with `--check` to verify the committed outputs match what tokens.ts would
 * produce right now; exits non-zero on drift. That check is what stops a recolor
 * from landing in tokens.ts while the assets silently keep the old palette —
 * which is exactly how skillshome-mark-color.svg sat on a superseded purple for
 * three weeks before this script existed.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { BRAND, LIGHT_THEME, DARK_THEME } from '../theme/tokens.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const BANNER = 'GENERATED by scripts/build-tokens.mjs from theme/tokens.ts — do not edit by hand.';

/** camelCase -> kebab-case (`blueDeep` -> `blue-deep`, `ink2` -> `ink2`). */
const kebab = (key) => key.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

/**
 * Emits `--brand-x: #rrggbb` plus, for hex values, `--brand-x-rgb: r, g, b` so
 * consumers can build alpha variants (`rgba(var(--brand-x-rgb), .16)`) without
 * re-typing the color — the alpha tints were the largest remaining group of
 * hardcoded hex before this existed.
 */
const block = (prefix, palette) =>
  Object.entries(palette)
    .flatMap(([key, value]) => {
      const name = `--brand-${prefix}${kebab(key)}`;
      const lines = [`  ${name}: ${value};`];
      const hex = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(value);
      if (hex) {
        const [r, g, b] = hex.slice(1).map((c) => parseInt(c, 16));
        lines.push(`  ${name}-rgb: ${r}, ${g}, ${b};`);
      }
      return lines;
    })
    .join('\n');

const tokensCss = `/* ${BANNER} */

:root {
${block('', BRAND)}

${block('light-', LIGHT_THEME)}

${block('dark-', DARK_THEME)}
}
`;

// Chevron path geometry on the 64x64 grid (from the brand spec). Geometry is
// fixed and lives here; only the fills come from tokens.
const CHEVRON = {
  bottom: 'M13 57 L32 38 L51 57 L44 57 L32 45 L20 57 Z',
  middle: 'M17 38 L32 23 L47 38 L40.8 38 L32 29.2 L23.2 38 Z',
  top: 'M21 21 L32 10 L43 21 L37.6 21 L32 15.4 L26.4 21 Z',
};

// The bare mark is drawn with NO background tile (design_system_brass README §6),
// and its viewBox is tightened to the artwork bounds (x13–51 / y10–57). A
// 0 0 64 64 box left ~40% empty space, rendering the mark undersized beside a
// 16px wordmark. Below ~20px use the mono SVG — a three-step ramp turns to mud.
const MARK_VIEWBOX = '11 8 42 51';

const svgOpen = (viewBox, label) => {
  const [, , w, h] = viewBox.split(' ');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${w}" height="${h}" role="img" aria-label="${label}">`;
};

/**
 * Three separately-filled chevrons. `fills` is { bottom, middle, top }.
 * The mark brightens DOWNWARD — the bottom chevron is the brightest. Inverted it
 * reads as a different mark (README §6).
 */
const tricolor = (title, fills, indent = '  ') =>
  `${svgOpen(MARK_VIEWBOX, 'SkillsHome')}\n` +
  `  <title>${title}</title>\n` +
  `${indent}<path d="${CHEVRON.bottom}" fill="${fills.bottom}"></path>\n` +
  `${indent}<path d="${CHEVRON.middle}" fill="${fills.middle}"></path>\n` +
  `${indent}<path d="${CHEVRON.top}" fill="${fills.top}"></path>\n` +
  `</svg>\n`;

/** Single-fill variants — one <g fill> wrapping all three chevrons. */
const monotone = (title, fill) =>
  `${svgOpen(MARK_VIEWBOX, 'SkillsHome')}\n` +
  `  <title>${title}</title>\n` +
  `  <g fill="${fill}">\n` +
  `    <path d="${CHEVRON.bottom}"></path>\n` +
  `    <path d="${CHEVRON.middle}"></path>\n` +
  `    <path d="${CHEVRON.top}"></path>\n` +
  `  </g>\n` +
  `</svg>\n`;

// Deepened brass ramp for the mark on light/paper backgrounds — from the
// SkillsHomeLogo `light` variant. Graphic-only values; not tokens.
const MARK_LIGHT = { bottom: BRAND.brass, middle: '#b3812c', top: '#6d5120' };

// Rounded-square PWA/app icon. This is the one lockup that keeps a tile — a
// maskable icon must fill its safe area. Warm-black tile, dark-ramp chevrons.
const appIcon =
  `${svgOpen('0 0 80 80', 'SkillsHome app icon')}\n` +
  `  <title>SkillsHome — app icon</title>\n` +
  `  <rect width="80" height="80" rx="18" fill="${DARK_THEME.bg}"></rect>\n` +
  `  <g transform="translate(17.6 17.6) scale(0.7)">\n` +
  `    <path d="${CHEVRON.bottom}" fill="${BRAND.brassLight}"></path>\n` +
  `    <path d="${CHEVRON.middle}" fill="${BRAND.brass}"></path>\n` +
  `    <path d="${CHEVRON.top}" fill="${BRAND.brassDeepMark}"></path>\n` +
  `  </g>\n` +
  `</svg>\n`;

const outputs = {
  'theme/tokens.css': tokensCss,
  'logo/assets/skillshome-icon.svg': appIcon,
  'logo/assets/skillshome-mark-color.svg': tricolor(
    'SkillsHome — Ascending Facets (for light backgrounds)',
    MARK_LIGHT,
  ),
  'logo/assets/skillshome-mark-color-dark.svg': tricolor(
    'SkillsHome — Ascending Facets (for dark backgrounds)',
    { bottom: BRAND.brassLight, middle: BRAND.brass, top: BRAND.brassDeepMark },
  ),
  'logo/assets/skillshome-mark-mono.svg': monotone(
    'SkillsHome — single colour (flat brass; use below ~20px)',
    BRAND.brass,
  ),
  'logo/assets/skillshome-mark-reversed.svg': monotone(
    'SkillsHome — reversed (single colour, for photo backgrounds)',
    BRAND.white,
  ),
};

/**
 * sharp is an optional dependency: it isn't installed in this submodule, so we
 * borrow the consuming repo's copy when there is one. Without it the PNG marks
 * can't be re-rendered, which is a hard failure for a recolor but fine for a
 * CI drift check that only reads text outputs.
 */
async function loadSharp() {
  const require = createRequire(import.meta.url);
  for (const from of [ROOT, join(ROOT, '..')]) {
    try {
      return (await import(pathToFileURL(require.resolve('sharp', { paths: [from] })).href)).default;
    } catch {
      /* try the next location */
    }
  }
  return null;
}

/** PNG marks rendered from the app-icon SVG — same source, so they can't diverge. */
const RASTERS = [
  ['logo/assets/icon-192.png', 192],
  ['logo/assets/icon-512.png', 512],
];

const stale = [];
for (const [path, content] of Object.entries(outputs)) {
  const abs = join(ROOT, path);
  const current = (() => {
    try {
      return readFileSync(abs, 'utf8');
    } catch {
      return null;
    }
  })();

  if (current === content) continue;
  stale.push(path);
  if (CHECK) continue;

  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}

const sharp = await loadSharp();
if (!sharp) {
  const note =
    'sharp is not resolvable — skipping the PNG marks (icon-192/512).\n' +
    'Run this from a repo that has sharp installed (e.g. skillshome-app) whenever a\n' +
    'brand color changes, or the rasters will lag the palette.';
  if (!CHECK) {
    console.error(note);
    process.exit(1);
  }
  console.warn(`Note: ${note}`);
} else {
  const iconSvg = Buffer.from(outputs['logo/assets/skillshome-icon.svg']);
  for (const [path, size] of RASTERS) {
    const abs = join(ROOT, path);
    const rendered = await sharp(iconSvg, { density: 384 })
      .resize(size, size)
      .png({ compressionLevel: 9 })
      .toBuffer();

    let current = null;
    try {
      current = readFileSync(abs);
    } catch {
      /* missing counts as stale */
    }
    // Re-encoding is deterministic for a given sharp/libvips build, so a byte
    // compare is a valid drift signal here.
    if (current && current.equals(rendered)) continue;
    stale.push(path);
    if (CHECK) continue;
    writeFileSync(abs, rendered);
  }
}

if (CHECK && stale.length) {
  console.error(
    `Brand assets are out of sync with theme/tokens.ts:\n` +
      stale.map((p) => `  - ${p}`).join('\n') +
      `\n\nRun \`npm run build\` in ${relative(process.cwd(), ROOT) || '.'} and commit the result.`,
  );
  process.exit(1);
}

console.log(
  CHECK
    ? 'Brand assets are in sync with theme/tokens.ts.'
    : stale.length
      ? `Regenerated ${stale.length} file(s):\n` + stale.map((p) => `  - ${p}`).join('\n')
      : 'Brand assets already up to date.',
);
